name: CI/CD Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test_build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint the Code
        run: pnpm lint

      - name: Run type-check
        run: pnpm type-check
      #
      # - name: Generate CHANGELOG
      #   run: npx auto-changelog --commit-limit false -o CHANGELOG.md
      #
      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "github-actions@github.com"
      #
      # - name: Commit and Push Changelog
      #   run: |
      #     git add CHANGELOG.md
      #     git diff --cached --quiet || git commit -m "chore(release): update CHANGELOG"
      #     git push origin master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #
      - name: Build the Package
        run: pnpm build

      - name: Run release-it
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          git pull origin master --rebase || true
          pnpm release-it --ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
